// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/product/v1/product.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result int32

const (
	Result_SUCCESS Result = 0
	Result_FAILURE Result = 1
	Result_QUEUED  Result = 2
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
		2: "QUEUED",
	}
	Result_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
		"QUEUED":  2,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_api_product_v1_product_proto_enumTypes[0].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_api_product_v1_product_proto_enumTypes[0]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{0}
}

type SeckillStatus int32

const (
	SeckillStatus_SECKILL_STATUS_WAITING    SeckillStatus = 0
	SeckillStatus_SECKILL_STATUS_PROCESSING SeckillStatus = 1
	SeckillStatus_SECKILL_STATUS_SUCCESS    SeckillStatus = 2
	SeckillStatus_SECKILL_STATUS_SOLD_OUT   SeckillStatus = 3
	SeckillStatus_SECKILL_STATUS_DEGRADED   SeckillStatus = 4
	SeckillStatus_SECKILL_STATUS_FAILED     SeckillStatus = 5
)

// Enum value maps for SeckillStatus.
var (
	SeckillStatus_name = map[int32]string{
		0: "SECKILL_STATUS_WAITING",
		1: "SECKILL_STATUS_PROCESSING",
		2: "SECKILL_STATUS_SUCCESS",
		3: "SECKILL_STATUS_SOLD_OUT",
		4: "SECKILL_STATUS_DEGRADED",
		5: "SECKILL_STATUS_FAILED",
	}
	SeckillStatus_value = map[string]int32{
		"SECKILL_STATUS_WAITING":    0,
		"SECKILL_STATUS_PROCESSING": 1,
		"SECKILL_STATUS_SUCCESS":    2,
		"SECKILL_STATUS_SOLD_OUT":   3,
		"SECKILL_STATUS_DEGRADED":   4,
		"SECKILL_STATUS_FAILED":     5,
	}
)

func (x SeckillStatus) Enum() *SeckillStatus {
	p := new(SeckillStatus)
	*p = x
	return p
}

func (x SeckillStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeckillStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_product_v1_product_proto_enumTypes[1].Descriptor()
}

func (SeckillStatus) Type() protoreflect.EnumType {
	return &file_api_product_v1_product_proto_enumTypes[1]
}

func (x SeckillStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeckillStatus.Descriptor instead.
func (SeckillStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{1}
}

type SeckillReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillReq) Reset() {
	*x = SeckillReq{}
	mi := &file_api_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillReq) ProtoMessage() {}

func (x *SeckillReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillReq.ProtoReflect.Descriptor instead.
func (*SeckillReq) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *SeckillReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type SeckillResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           Result                 `protobuf:"varint,1,opt,name=res,proto3,enum=api.product.v1.Result" json:"res,omitempty"`
	RequestID     string                 `protobuf:"bytes,2,opt,name=requestID,proto3" json:"requestID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillResp) Reset() {
	*x = SeckillResp{}
	mi := &file_api_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillResp) ProtoMessage() {}

func (x *SeckillResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillResp.ProtoReflect.Descriptor instead.
func (*SeckillResp) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *SeckillResp) GetRes() Result {
	if x != nil {
		return x.Res
	}
	return Result_SUCCESS
}

func (x *SeckillResp) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

type GetSeckillStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestID     string                 `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeckillStatusReq) Reset() {
	*x = GetSeckillStatusReq{}
	mi := &file_api_product_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillStatusReq) ProtoMessage() {}

func (x *GetSeckillStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillStatusReq.ProtoReflect.Descriptor instead.
func (*GetSeckillStatusReq) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *GetSeckillStatusReq) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

type GetSeckillStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SeckillStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=api.product.v1.SeckillStatus" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	UserID        int64                  `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	ProductID     int64                  `protobuf:"varint,4,opt,name=productID,proto3" json:"productID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeckillStatusResp) Reset() {
	*x = GetSeckillStatusResp{}
	mi := &file_api_product_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillStatusResp) ProtoMessage() {}

func (x *GetSeckillStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillStatusResp.ProtoReflect.Descriptor instead.
func (*GetSeckillStatusResp) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetSeckillStatusResp) GetStatus() SeckillStatus {
	if x != nil {
		return x.Status
	}
	return SeckillStatus_SECKILL_STATUS_WAITING
}

func (x *GetSeckillStatusResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GetSeckillStatusResp) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetSeckillStatusResp) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

type DeductStockSagaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockSagaReq) Reset() {
	*x = DeductStockSagaReq{}
	mi := &file_api_product_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockSagaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockSagaReq) ProtoMessage() {}

func (x *DeductStockSagaReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockSagaReq.ProtoReflect.Descriptor instead.
func (*DeductStockSagaReq) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *DeductStockSagaReq) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *DeductStockSagaReq) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DeductStockSagaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockSagaResp) Reset() {
	*x = DeductStockSagaResp{}
	mi := &file_api_product_v1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockSagaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockSagaResp) ProtoMessage() {}

func (x *DeductStockSagaResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockSagaResp.ProtoReflect.Descriptor instead.
func (*DeductStockSagaResp) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{5}
}

func (x *DeductStockSagaResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RestoreStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreStockReq) Reset() {
	*x = RestoreStockReq{}
	mi := &file_api_product_v1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStockReq) ProtoMessage() {}

func (x *RestoreStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStockReq.ProtoReflect.Descriptor instead.
func (*RestoreStockReq) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreStockReq) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *RestoreStockReq) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RestoreStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreStockResp) Reset() {
	*x = RestoreStockResp{}
	mi := &file_api_product_v1_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStockResp) ProtoMessage() {}

func (x *RestoreStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStockResp.ProtoReflect.Descriptor instead.
func (*RestoreStockResp) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{7}
}

func (x *RestoreStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReq) Reset() {
	*x = GetProductReq{}
	mi := &file_api_product_v1_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReq) ProtoMessage() {}

func (x *GetProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReq.ProtoReflect.Descriptor instead.
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductReq) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

type GetProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Price         int32                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResp) Reset() {
	*x = GetProductResp{}
	mi := &file_api_product_v1_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResp) ProtoMessage() {}

func (x *GetProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResp.ProtoReflect.Descriptor instead.
func (*GetProductResp) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{9}
}

func (x *GetProductResp) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *GetProductResp) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetProductResp) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

var File_api_product_v1_product_proto protoreflect.FileDescriptor

const file_api_product_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x1capi/product/v1/product.proto\x12\x0eapi.product.v1\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\n" +
	"SeckillReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\"U\n" +
	"\vSeckillResp\x12(\n" +
	"\x03res\x18\x01 \x01(\x0e2\x16.api.product.v1.ResultR\x03res\x12\x1c\n" +
	"\trequestID\x18\x02 \x01(\tR\trequestID\"3\n" +
	"\x13GetSeckillStatusReq\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\"\x9b\x01\n" +
	"\x14GetSeckillStatusResp\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.api.product.v1.SeckillStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\x03R\x06userID\x12\x1c\n" +
	"\tproductID\x18\x04 \x01(\x03R\tproductID\"J\n" +
	"\x12DeductStockSagaReq\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\x03R\tproductID\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"/\n" +
	"\x13DeductStockSagaResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"G\n" +
	"\x0fRestoreStockReq\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\x03R\tproductID\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\",\n" +
	"\x10RestoreStockResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\rGetProductReq\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\x03R\tproductID\"Z\n" +
	"\x0eGetProductResp\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\x03R\tproductID\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x05R\x05price\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x05R\x05stock*.\n" +
	"\x06Result\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x01\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x02*\xbb\x01\n" +
	"\rSeckillStatus\x12\x1a\n" +
	"\x16SECKILL_STATUS_WAITING\x10\x00\x12\x1d\n" +
	"\x19SECKILL_STATUS_PROCESSING\x10\x01\x12\x1a\n" +
	"\x16SECKILL_STATUS_SUCCESS\x10\x02\x12\x1b\n" +
	"\x17SECKILL_STATUS_SOLD_OUT\x10\x03\x12\x1b\n" +
	"\x17SECKILL_STATUS_DEGRADED\x10\x04\x12\x19\n" +
	"\x15SECKILL_STATUS_FAILED\x10\x052\xa5\x04\n" +
	"\aProduct\x12[\n" +
	"\aSeckill\x12\x1a.api.product.v1.SeckillReq\x1a\x1b.api.product.v1.SeckillResp\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/seckill\x12}\n" +
	"\x10GetSeckillStatus\x12#.api.product.v1.GetSeckillStatusReq\x1a$.api.product.v1.GetSeckillStatusResp\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/seckill/status\x12\x84\x01\n" +
	"\x0fDeductStockSaga\x12\".api.product.v1.DeductStockSagaReq\x1a#.api.product.v1.DeductStockSagaResp\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/seckill/saga/deductStock\x12Q\n" +
	"\fRestoreStock\x12\x1f.api.product.v1.RestoreStockReq\x1a .api.product.v1.RestoreStockResp\x12d\n" +
	"\n" +
	"GetProduct\x12\x1d.api.product.v1.GetProductReq\x1a\x1e.api.product.v1.GetProductResp\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/productB-\n" +
	"\x0eapi.product.v1P\x01Z\x19seckill/api/product/v1;v1b\x06proto3"

var (
	file_api_product_v1_product_proto_rawDescOnce sync.Once
	file_api_product_v1_product_proto_rawDescData []byte
)

func file_api_product_v1_product_proto_rawDescGZIP() []byte {
	file_api_product_v1_product_proto_rawDescOnce.Do(func() {
		file_api_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_product_v1_product_proto_rawDesc), len(file_api_product_v1_product_proto_rawDesc)))
	})
	return file_api_product_v1_product_proto_rawDescData
}

var file_api_product_v1_product_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_product_v1_product_proto_goTypes = []any{
	(Result)(0),                  // 0: api.product.v1.Result
	(SeckillStatus)(0),           // 1: api.product.v1.SeckillStatus
	(*SeckillReq)(nil),           // 2: api.product.v1.SeckillReq
	(*SeckillResp)(nil),          // 3: api.product.v1.SeckillResp
	(*GetSeckillStatusReq)(nil),  // 4: api.product.v1.GetSeckillStatusReq
	(*GetSeckillStatusResp)(nil), // 5: api.product.v1.GetSeckillStatusResp
	(*DeductStockSagaReq)(nil),   // 6: api.product.v1.DeductStockSagaReq
	(*DeductStockSagaResp)(nil),  // 7: api.product.v1.DeductStockSagaResp
	(*RestoreStockReq)(nil),      // 8: api.product.v1.RestoreStockReq
	(*RestoreStockResp)(nil),     // 9: api.product.v1.RestoreStockResp
	(*GetProductReq)(nil),        // 10: api.product.v1.GetProductReq
	(*GetProductResp)(nil),       // 11: api.product.v1.GetProductResp
}
var file_api_product_v1_product_proto_depIdxs = []int32{
	0,  // 0: api.product.v1.SeckillResp.res:type_name -> api.product.v1.Result
	1,  // 1: api.product.v1.GetSeckillStatusResp.status:type_name -> api.product.v1.SeckillStatus
	2,  // 2: api.product.v1.Product.Seckill:input_type -> api.product.v1.SeckillReq
	4,  // 3: api.product.v1.Product.GetSeckillStatus:input_type -> api.product.v1.GetSeckillStatusReq
	6,  // 4: api.product.v1.Product.DeductStockSaga:input_type -> api.product.v1.DeductStockSagaReq
	8,  // 5: api.product.v1.Product.RestoreStock:input_type -> api.product.v1.RestoreStockReq
	10, // 6: api.product.v1.Product.GetProduct:input_type -> api.product.v1.GetProductReq
	3,  // 7: api.product.v1.Product.Seckill:output_type -> api.product.v1.SeckillResp
	5,  // 8: api.product.v1.Product.GetSeckillStatus:output_type -> api.product.v1.GetSeckillStatusResp
	7,  // 9: api.product.v1.Product.DeductStockSaga:output_type -> api.product.v1.DeductStockSagaResp
	9,  // 10: api.product.v1.Product.RestoreStock:output_type -> api.product.v1.RestoreStockResp
	11, // 11: api.product.v1.Product.GetProduct:output_type -> api.product.v1.GetProductResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_product_v1_product_proto_init() }
func file_api_product_v1_product_proto_init() {
	if File_api_product_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_product_v1_product_proto_rawDesc), len(file_api_product_v1_product_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_product_v1_product_proto_goTypes,
		DependencyIndexes: file_api_product_v1_product_proto_depIdxs,
		EnumInfos:         file_api_product_v1_product_proto_enumTypes,
		MessageInfos:      file_api_product_v1_product_proto_msgTypes,
	}.Build()
	File_api_product_v1_product_proto = out.File
	file_api_product_v1_product_proto_goTypes = nil
	file_api_product_v1_product_proto_depIdxs = nil
}
