// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.0
// source: api/product/v1/product.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProductDeductStockSaga = "/api.product.v1.Product/DeductStockSaga"
const OperationProductGetProduct = "/api.product.v1.Product/GetProduct"
const OperationProductGetSeckillStatus = "/api.product.v1.Product/GetSeckillStatus"
const OperationProductSeckill = "/api.product.v1.Product/Seckill"

type ProductHTTPServer interface {
	DeductStockSaga(context.Context, *DeductStockSagaReq) (*DeductStockSagaResp, error)
	GetProduct(context.Context, *GetProductReq) (*GetProductResp, error)
	GetSeckillStatus(context.Context, *GetSeckillStatusReq) (*GetSeckillStatusResp, error)
	Seckill(context.Context, *SeckillReq) (*SeckillResp, error)
}

func RegisterProductHTTPServer(s *http.Server, srv ProductHTTPServer) {
	r := s.Route("/")
	r.POST("/api/seckill", _Product_Seckill0_HTTP_Handler(srv))
	r.POST("/api/seckill/status", _Product_GetSeckillStatus0_HTTP_Handler(srv))
	r.POST("/api/seckill/saga/deductStock", _Product_DeductStockSaga0_HTTP_Handler(srv))
	r.POST("/api/product", _Product_GetProduct0_HTTP_Handler(srv))
}

func _Product_Seckill0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SeckillReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductSeckill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Seckill(ctx, req.(*SeckillReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SeckillResp)
		return ctx.Result(200, reply)
	}
}

func _Product_GetSeckillStatus0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSeckillStatusReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductGetSeckillStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSeckillStatus(ctx, req.(*GetSeckillStatusReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSeckillStatusResp)
		return ctx.Result(200, reply)
	}
}

func _Product_DeductStockSaga0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeductStockSagaReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductDeductStockSaga)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeductStockSaga(ctx, req.(*DeductStockSagaReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeductStockSagaResp)
		return ctx.Result(200, reply)
	}
}

func _Product_GetProduct0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProductReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductGetProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProduct(ctx, req.(*GetProductReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProductResp)
		return ctx.Result(200, reply)
	}
}

type ProductHTTPClient interface {
	DeductStockSaga(ctx context.Context, req *DeductStockSagaReq, opts ...http.CallOption) (rsp *DeductStockSagaResp, err error)
	GetProduct(ctx context.Context, req *GetProductReq, opts ...http.CallOption) (rsp *GetProductResp, err error)
	GetSeckillStatus(ctx context.Context, req *GetSeckillStatusReq, opts ...http.CallOption) (rsp *GetSeckillStatusResp, err error)
	Seckill(ctx context.Context, req *SeckillReq, opts ...http.CallOption) (rsp *SeckillResp, err error)
}

type ProductHTTPClientImpl struct {
	cc *http.Client
}

func NewProductHTTPClient(client *http.Client) ProductHTTPClient {
	return &ProductHTTPClientImpl{client}
}

func (c *ProductHTTPClientImpl) DeductStockSaga(ctx context.Context, in *DeductStockSagaReq, opts ...http.CallOption) (*DeductStockSagaResp, error) {
	var out DeductStockSagaResp
	pattern := "/api/seckill/saga/deductStock"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductDeductStockSaga))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductHTTPClientImpl) GetProduct(ctx context.Context, in *GetProductReq, opts ...http.CallOption) (*GetProductResp, error) {
	var out GetProductResp
	pattern := "/api/product"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductGetProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductHTTPClientImpl) GetSeckillStatus(ctx context.Context, in *GetSeckillStatusReq, opts ...http.CallOption) (*GetSeckillStatusResp, error) {
	var out GetSeckillStatusResp
	pattern := "/api/seckill/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductGetSeckillStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductHTTPClientImpl) Seckill(ctx context.Context, in *SeckillReq, opts ...http.CallOption) (*SeckillResp, error) {
	var out SeckillResp
	pattern := "/api/seckill"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductSeckill))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
