// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsSoldOut(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_SOLD_OUT.String() && e.Code == 404
}

func ErrorSoldOut(format string, args ...interface{}) *errors.Error {
	return errors.New(404, UserErrorReason_SOLD_OUT.String(), fmt.Sprintf(format, args...))
}

func IsServiceBusy(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_SERVICE_BUSY.String() && e.Code == 500
}

func ErrorServiceBusy(format string, args ...interface{}) *errors.Error {
	return errors.New(500, UserErrorReason_SERVICE_BUSY.String(), fmt.Sprintf(format, args...))
}

func IsQueueTimeout(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_QUEUE_TIMEOUT.String() && e.Code == 504
}

func ErrorQueueTimeout(format string, args ...interface{}) *errors.Error {
	return errors.New(504, UserErrorReason_QUEUE_TIMEOUT.String(), fmt.Sprintf(format, args...))
}

func IsQueueDuplicate(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_QUEUE_DUPLICATE.String() && e.Code == 409
}

func ErrorQueueDuplicate(format string, args ...interface{}) *errors.Error {
	return errors.New(409, UserErrorReason_QUEUE_DUPLICATE.String(), fmt.Sprintf(format, args...))
}

func IsRequestNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_REQUEST_NOT_FOUND.String() && e.Code == 404
}

func ErrorRequestNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, UserErrorReason_REQUEST_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsBalanceInsufficient(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_BALANCE_INSUFFICIENT.String() && e.Code == 403
}

func ErrorBalanceInsufficient(format string, args ...interface{}) *errors.Error {
	return errors.New(403, UserErrorReason_BALANCE_INSUFFICIENT.String(), fmt.Sprintf(format, args...))
}
