// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"seckill/app/product/internal/biz"
	"seckill/app/product/internal/conf"
	"seckill/app/product/internal/data"
	"seckill/app/product/internal/server"
	"seckill/app/product/internal/service"
	"seckill/app/product/internal/worker"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, dtmCfg *conf.Dtm, seckill *conf.Seckill, logger log.Logger) (*kratos.App, func(), error) {
	pool, err := data.NewPgxPool(confData)
	if err != nil {
		return nil, nil, err
	}
	workers := server.NewRiverWorkers()
	riverClient, err := server.NewRiverClient(pool, workers, seckill)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, pool, riverClient)
	if err != nil {
		return nil, nil, err
	}
	productRepoImpl := data.NewProductRepo(dataData, logger)
	seckillRequestRepoImpl := data.NewSeckillRequestRepo(dataData, logger)
	seckillJobRepoImpl := data.NewSeckillJobRepo(riverClient)
	sagaData := data.NewSAGAData(dtmCfg)
	productUsecase := biz.NewProductUsecase(productRepoImpl, seckillRequestRepoImpl, seckillJobRepoImpl, sagaData, seckill, logger)
	seckillWorker := worker.NewSeckillWorker(productUsecase, logger)
	messagingWorker := worker.NewMessagingWorker(logger)
	productService := service.NewProductService(productUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, productService, logger)
	httpServer := server.NewHTTPServer(confServer, productService, logger)
	clientv3Client := server.NewEtcdClient(registry)
	registrar := server.NewRegistrar(clientv3Client)
	riverServer := server.NewRiverServer(riverClient)
	server.RegisterRiverWorkers(workers, seckillWorker, messagingWorker)
	app := newApp(logger, grpcServer, httpServer, registrar, riverServer)
	return app, func() {
		cleanup()
	}, nil
}
