apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: dtm
  name: dtm-cm0
data:
  config.yml: |
    Store:
      Driver: postgres
      Host: postgres
      Port: 5432
      User: postgres
      Password: postgres
      Db: dtm
    HTTPPort: 36789
    GrpcPort: 36790
